"""add rbac workflow tables

Revision ID: fec453e3f128
Revises: d2cded87e7ca
Create Date: 2025-11-11 18:08:45.096284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fec453e3f128'
down_revision: Union[str, None] = 'd2cded87e7ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission_schemes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permission_scheme_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scheme_id', sa.UUID(), nullable=False),
    sa.Column('permission_key', sa.String(length=100), nullable=False),
    sa.Column('principal_type', sa.String(length=50), nullable=False),
    sa.Column('principal_identifier', sa.String(length=255), nullable=False),
    sa.Column('constraints', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['scheme_id'], ['permission_schemes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_statuses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_transitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('from_status_id', sa.UUID(), nullable=False),
    sa.Column('to_status_id', sa.UUID(), nullable=False),
    sa.Column('allowed_roles', sa.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['from_status_id'], ['workflow_statuses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_status_id'], ['workflow_statuses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('organizations', sa.Column('default_role', sa.String(length=50), nullable=False))
    op.add_column('project_members', sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('project_members', sa.Column('added_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'project_members', 'users', ['added_by'], ['id'], ondelete='SET NULL')
    op.add_column('projects', sa.Column('lead_id', sa.UUID(), nullable=True))
    op.add_column('projects', sa.Column('workflow_id', sa.UUID(), nullable=True))
    op.add_column('projects', sa.Column('permission_scheme_id', sa.UUID(), nullable=True))
    op.add_column('projects', sa.Column('key_sequence', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'projects', 'permission_schemes', ['permission_scheme_id'], ['id'])
    op.create_foreign_key(None, 'projects', 'users', ['lead_id'], ['id'])
    op.create_foreign_key(None, 'projects', 'workflows', ['workflow_id'], ['id'])
    op.add_column('user_organizations', sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_organizations', 'permissions')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'key_sequence')
    op.drop_column('projects', 'permission_scheme_id')
    op.drop_column('projects', 'workflow_id')
    op.drop_column('projects', 'lead_id')
    op.drop_constraint(None, 'project_members', type_='foreignkey')
    op.drop_column('project_members', 'added_by')
    op.drop_column('project_members', 'permissions')
    op.drop_column('organizations', 'default_role')
    op.drop_table('workflow_transitions')
    op.drop_table('workflow_statuses')
    op.drop_table('permission_scheme_rules')
    op.drop_table('workflows')
    op.drop_table('permission_schemes')
    # ### end Alembic commands ###
